# Generated by Django 6.0.5 on 2026-05-17 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Rak')),
                ('location', models.CharField(help_text='Contoh: Area depan kiri, Rak nomor 3', max_length=200, verbose_name='Lokasi Rak')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Kapasitas (unit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rak',
                'verbose_name_plural': 'Rak',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Supplier')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kontak Person')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('category', models.CharField(choices=[('operasional', 'Operasional'), ('gaji', 'Gaji Karyawan'), ('sewa', 'Sewa Tempat'), ('listrik', 'Listrik & Air'), ('transport', 'Transportasi'), ('perawatan', 'Perawatan'), ('lainnya', 'Lainnya')], default='operasional', max_length=50, verbose_name='Kategori')),
                ('description', models.CharField(max_length=300, verbose_name='Deskripsi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengeluaran',
                'verbose_name_plural': 'Pengeluaran',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('category', models.CharField(choices=[('jasa', 'Pendapatan Jasa'), ('sewa', 'Pendapatan Sewa'), ('lainnya', 'Lainnya')], default='lainnya', max_length=50, verbose_name='Kategori')),
                ('description', models.CharField(max_length=300, verbose_name='Deskripsi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pemasukan',
                'verbose_name_plural': 'Pemasukan',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True, verbose_name='Kode SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('ltr', 'Liter'), ('pack', 'Pack'), ('box', 'Box'), ('lusin', 'Lusin')], default='pcs', max_length=20, verbose_name='Satuan')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Beli')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Jual')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Gambar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('minimum_stock', models.PositiveIntegerField(default=5, help_text='Peringatan stok rendah jika di bawah ini', verbose_name='Stok Minimum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah Masuk')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Beli per Unit')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Otomatis dihitung dari jumlah x harga beli', max_digits=15, verbose_name='Total Harga')),
                ('date', models.DateField(verbose_name='Tanggal Masuk')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='store.product', verbose_name='Barang')),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='store.shelf', verbose_name='Rak Tujuan')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='store.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Stok Masuk',
                'verbose_name_plural': 'Stok Masuk',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Kode Transaksi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('debit', 'Kartu Debit'), ('credit', 'Kartu Kredit'), ('qris', 'QRIS'), ('transfer', 'Transfer Bank')], default='cash', max_length=20, verbose_name='Metode Pembayaran')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Diskon')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Uang Diterima')),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kembalian')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Pelanggan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Satuan')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Modal')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Keuntungan')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Barang')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.transaction', verbose_name='Transaksi')),
            ],
            options={
                'verbose_name': 'Item Transaksi',
                'verbose_name_plural': 'Item Transaksi',
            },
        ),
        migrations.CreateModel(
            name='ShelfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_placements', to='store.product', verbose_name='Barang')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_products', to='store.shelf', verbose_name='Rak')),
            ],
            options={
                'verbose_name': 'Penempatan Rak',
                'verbose_name_plural': 'Penempatan Rak',
                'unique_together': {('product', 'shelf')},
            },
        ),
    ]
